= Commands
ifdef::env-name[:relfilesuffix: .adoc]

Return to xref:index.adoc[index]

== Acknowledgement

Each command must be acknowledged with a `ack` (successful) or a `nack` (unsuccessful).

To reconcile which command the acknowledgement reefers to, the `transaction_id` is used.

So, a command with the `transaction_id` : `abcd1234`, when an acknowledgement is received with the same `transaction_id` it reefers to that command.

=== ACK

Indicates that the command with th given `transaction_id` has succeeded.

* Usage : client / server
* Indicator : `@`
* Arguments : `OK`
* Example : `@abcd1234OK\n`

=== NACK

Indicates that the command with th given `transaction_id` has failed.

* Usage : client / server
* Indicator : `@`
* Arguments : `KO`
* Example : `@abcd1234KO\n`

== Create Tunnel

Asks the server to create a Tunnel with the provided arguments.

The server responds with a `ack` means that the Tunnel has been created.

The server responds with a `nack` means that the Tunnel has not been created.

* Usage : client
* Indicator : `+`
* Arguments :

[cols="1,1,1,3"]
|===
|*Name*
|*Size*
|*Values*
|*Description*

|Tunnel type
|1 byte
|0 : Broadcast (all messages will be transferred to all Tunnel's listeners).
|Indicates the desired type of Tunnel (see values).

|Tunnel name
|n bytes
|
|Name of the Tunnel to create.
|===

* Example : `@abcd12340MyTunnel\n` => Asks to create a broadcast Tunnel `MyTunnel`.

== Listen to Tunnel

Asks the server to register the client as a listener of the given Tunnel.

The server responds with a `ack` means that the client is now listening the Tunnel.

The server responds with a `nack` means that the client isn't listening the Tunnel.

* Usage : client
* Indicator : `#`
* Arguments : <tunnel_name> (n bytes)
* Example : `#abcd1234MyTunnel\n` => Ask to listen to the Tunnel `MyTunnel`.

== Publish message to Tunnel

/!\ Only supporting string messages for now /!\

Has a client you can publish messages to a Tunnel. The Tunnel must exist, and you must be listening to it in order to succeed.

The message reconciliation, on the server-side, depend on the Tunnel's type. For a broadcast Tunnel, the message will be sent to all listeners except for the originator.

The server responds with a `ack` means that the message has been successfully registered.

The server responds with a `nack` means that the message hasn't been registered.

* Usage : client
* Indicator : `>`
* Arguments : `<tunnel_name> <message>` (Note that currently, the first space found act as separator between `tunnel_name` and `message`)
* Example : `>abcd1234MyTunnel Mon super message !\n` => Publish to the Tunnel `MyTunnel` the message `Mon super message !`.

== Receive message from Tunnel

/!\ Only supporting string messages for now /!\

The server send you messages for the Tunnel you are listening to.

You must respond with a `ack` when you successfully processed the message.

You must respond with a `nack` when you didn't process the message (currently the message will be lost but will change in the future).

* Usage : server
* Indicator : `<`
* Arguments : `<tunnel_name> <message>` (Note that currently, the first space found act as separator between `tunnel_name` and `message`)
* Example : `<abcd1234MyTunnel Mon super message !\n` => Indicates that the message `Mon super message !` has been published to the Tunnel `MyTunnel`.